# Generated by Django 5.2.13 on 2026-04-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="course",
            field=models.CharField(choices=[("Python", "Python")], max_length=120),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advance", "Advance"),
                ],
                max_length=20,
            ),
        ),
    ]
